### ISSUE TITLE
elFinder dropbox root folder error

### ISSUE THREAD

**Issue by rajasharma27** [nao-pon/elFinder-nightly-src#2]
i am facing problem connect dropbox full access app in elfinder. when i mount dropbox in elfinder with 
"/folder_name" it is working fine and mount successfully dropbox, but when i mount full dropbox without folder name  only with this " / " it return error "Unable to mount "dropbox", Root folder does not exists. please help me.

**Comment by rajasharma27** [comment]
i am facing problem connect dropbox full access app in elfinder. when i mount dropbox in elfinder with "/folder_name" it is working fine and mount successfully dropbox, but when i mount full dropbox without folder name only with this " / " it return error "Unable to mount "dropbox", Root folder does not exists. please help me.

"GET /test/elFinder/php/connector.minimal.php?cmd=netmount&protocol=dropbox&host=dropbox&path=%2F&user=done&pass=done&_=139543023676

its showing error "root folder does not exist"
please help me

**Comment by nao-pon** [comment]
@rajasharma27 There is no problem in my test case. Please show me your connector configuration.

**Comment by rajasharma27** [comment]
## this is my connector code

``` php
error_reporting(E_ALL); // Set E_ALL for debuging

include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderConnector.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinder.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeDriver.class.php';
include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeLocalFileSystem.class.php';
// Required for MySQL storage connector
// include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeMySQL.class.php';
// Required for FTP connector support
// include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeFTP.class.php';

/**
 * # Dropbox volume driver need "dropbox-php's Dropbox" and "PHP OAuth extension" or "PEAR's HTTP_OAUTH package"
 * * dropbox-php: http://www.dropbox-php.com/
 * * PHP OAuth extension: http://pecl.php.net/package/oauth
 * * PEAR's HTTP_OAUTH package: http://pear.php.net/package/http_oauth
 *  * HTTP_OAUTH package require HTTP_Request2 and Net_URL2
 */
// Required for Dropbox.com connector support
 include_once dirname(__FILE__).DIRECTORY_SEPARATOR.'elFinderVolumeDropbox.class.php';

// Dropbox driver need next two settings. You can get at https://www.dropbox.com/developers
 define('ELFINDER_DROPBOX_CONSUMERKEY',    '---------------');
 define('ELFINDER_DROPBOX_CONSUMERSECRET', '---------------');
// define('ELFINDER_DROPBOX_META_CACHE_PATH',''); // optional for `options['metaCachePath']`

/**
 * Simple function to demonstrate how to control file access using "accessControl" callback.
 * This method will disable accessing files/folders starting from '.' (dot)
 *
 * @param  string  $attr  attribute name (read|write|locked|hidden)
 * @param  string  $path  file path relative to volume root directory started with directory separator
 * @return bool|null
 **/
function access($attr, $path, $data, $volume) {
    return strpos(basename($path), '.') === 0       // if file/folder begins with '.' (dot)
        ? !($attr == 'read' || $attr == 'write')    // set read+write to false, other (locked+hidden) set to true
        :  null;                                    // else elFinder decide it itself
}


// Documentation for connector options:
// https://github.com/Studio-42/elFinder/wiki/Connector-configuration-options
$opts = array(
    'debug' => true,    
    'roots' => array(
        array(
            'driver'        => 'LocalFileSystem',   // driver for accessing file system (REQUIRED)
            'path'          => '../files',         // path to files (REQUIRED)
            'URL'           => dirname($_SERVER['PHP_SELF']).'/../files/', // URL to files (REQUIRED)
            'alias'         => 'Home',
            'accessControl' => 'access',             // disable and hide dot starting files (OPTIONAL)
            'mimeDetect'    => 'internal',
            'imgLib'        => 'auto',          
            'attributes'    => array(
            array(
                'pattern'   => '/.(elFinder|Images|Media|Text)/', // Dont write or delete to this and all subfolders
                'read'      => true,
                'write'     => false,
                'locked'    => true
                )   
            )

        )       
    )
);

// run elFinder
$connector = new elFinderConnector(new elFinder($opts));
$connector->run();
```

---

this code is working fine when i mount dropbox with folder name but when i mount full dropbox access it showing "root folder does not exist" i am using full access dropbox app.
please help me.

**Comment by rajasharma27** [comment]
this is my url request

http://localhost:8080/oldelfinder/php/connector.minimal.php?cmd=netmount&protocol=dropbox&host=dropbox&path=%2F&user=done&pass=done&_=1449769171656

## return json

``` json
{"error":["errNetMount","dropbox","Root folder does not exists."],"debug":{"connector":"php","phpver":"5.3.18","time":0.023507118225098,"memory":"3601Kb \/ 3560Kb \/ 128M","upload":"","volumes":[{"id":"l1_","name":"localfilesystem","mimeDetect":"internal","imgLib":"gd"}],"mountErrors":["Driver \"elFinderVolumeDropbox\" : Path undefined."]}}
```

**Comment by nao-pon** [comment]
Please try client configuration [`requesttype`](https://github.com/Studio-42/elFinder/wiki/Client-configuration-options#requesttype) to 'post'.

**Comment by rajasharma27** [comment]
sir in your test code
http://hypweb.net/elFinder-nightly/demo/2.1/php/connector.minimal.php?cmd=netmount&protocol=dropbox&host=dropbox&path=%2F&user=done&pass=done&_=1449848418285

{"added":[{"rev":"root","name":"Dropbox.com","mime":"directory","size":0,"ts":1449848484,"dirs":1,"url":"1","hash":"d4_Lw","csscls":"elfinder-navbar-root-dropbox","volumeid":"d4_","read":1,"write":1,"locked":1,"uiCmdMap":[],"disabled":["chmod"],"netkey":"41dfa9834da482938bdebe823d6529e5"}],"debug":{"connector":"php","phpver":"5.5.30","time":0.02924919128418,"memory":"1945Kb \/ 949Kb \/ 256M","upload":"","volumes":[{"id":"l1_","name":"localfilesystem","mimeDetect":"finfo","imgLib":"imagick"},{"id":"l2_","name":"localfilesystem","mimeDetect":"finfo","imgLib":"imagick"},{"id":"d3_","name":"dropboxdemo","mimeDetect":"internal","imgLib":"imagick"}],"mountErrors":[]}}

---

in my case
http://localhost:8080/oldelfinder/php/connector.minimal.php?cmd=netmount&protocol=dropbox&host=dropbox&path=%2F&user=done&pass=done&_=1449848202130

{"error":["errNetMount","dropbox","Root folder does not exists."],"debug":{"connector":"php","phpver":"5.3.18","time":0.023572206497192,"memory":"3601Kb \/ 3560Kb \/ 128M","upload":"","volumes":[{"id":"l1_","name":"localfilesystem","mimeDetect":"internal","imgLib":"gd"}],"mountErrors":["Driver \"elFinderVolumeDropbox\" : Path undefined."]}}

in your code return
root name  "Dropbox.com"
but my code return root name only dropbox
and showing error 
"dropbox","Root folder does not exists."],"

**Comment by rajasharma27** [comment]
please help me

**Comment by rajasharma27** [comment]
in which file i change this "client configuration requesttype to 'post'

**Comment by nao-pon** [comment]
In your html of front end.

``` html
<script type="text/javascript" charset="utf-8">
    $().ready(function() {
        var elf = $('#elfinder').elfinder({
            requesttype: 'post',
            url : 'php/connector.php'  // connector URL (REQUIRED)
        }).elfinder('instance');            
    });
</script>
```

**Comment by rajasharma27** [comment]
sir, after putting your suggest code, problem is same.
always mount specific folder not mount full dropbox.

**Comment by nao-pon** [comment]
Well, it seems to remove the "%2F" on the your web server. I have no idea. Please check your server configuration.

**Comment by rajasharma27** [comment]
sir,
i am using your dropbox code which i download from
https://github.com/xoopscube/xupdate/tree/master/xoops_trust_path

and your elfinder code which i download from

https://github.com/nao-pon/elFinder-nightly 2.1.2

nothing change your code only add my full access dropbox php app code and security code

.sir please help me.
i am facing full dropbox access error "root folder does not exist"
give me some solution.

**Comment by nao-pon** [comment]
Why do you use https://github.com/xoopscube/xupdate/tree/master/xoops_trust_path?

**Comment by rajasharma27** [comment]
sir, i am using only pear or oauth package which provided by you.

**Comment by nao-pon** [comment]
OK.So, try the following
- add next code your php connector (ex. php/connector.minimal.php)

``` php
function debug() {
    $args = func_get_args();
    ob_start();
    foreach($args as $arg) {
        //debug_print_backtrace();
        var_dump($arg);
    }
    $str = ob_get_clean();
    file_put_contents(dirname(__FILE__) . '/debug.txt', $str . "\n", FILE_APPEND);
}
```
- and add `debug()` into php/elFinderVolumeDriver.class.php L.707

``` php
    public function mount(array $opts) {
        if (!isset($opts['path']) || $opts['path'] === '') {
            return $this->setError('Path undefined.');;
        }
```

to

``` php
    public function mount(array $opts) {
        debug($opts, $_POST, $_GET);
        if (!isset($opts['path']) || $opts['path'] === '') {
            return $this->setError('Path undefined.');;
        }
```
- Try netmount of Dropbox
- Check php/debug.txt and show me.

**Comment by rajasharma27** [comment]
debug result

array(7) {
  ["driver"]=>
  string(15) "LocalFileSystem"
  ["path"]=>
  string(9) "../files/"
  ["URL"]=>
  string(23) "/elfinder/php/../files/"
  ["uploadDeny"]=>
  array(1) {
    [0]=>
    string(3) "all"
  }
  ["uploadAllow"]=>
  array(2) {
    [0]=>
    string(5) "image"
    [1]=>
    string(10) "text/plain"
  }
  ["uploadOrder"]=>
  array(2) {
    [0]=>
    string(4) "deny"
    [1]=>
    string(5) "allow"
  }
  ["accessControl"]=>
  string(6) "access"
}
array(0) {
}
array(5) {
  ["cmd"]=>
  string(4) "open"
  ["target"]=>
  string(5) "l1_XA"
  ["init"]=>
  string(1) "1"
  ["tree"]=>
  string(1) "1"
  ["_"]=>
  string(13) "1449986007015"
}

array(7) {
  ["driver"]=>
  string(15) "LocalFileSystem"
  ["path"]=>
  string(9) "../files/"
  ["URL"]=>
  string(23) "/elfinder/php/../files/"
  ["uploadDeny"]=>
  array(1) {
    [0]=>
    string(3) "all"
  }
  ["uploadAllow"]=>
  array(2) {
    [0]=>
    string(5) "image"
    [1]=>
    string(10) "text/plain"
  }
  ["uploadOrder"]=>
  array(2) {
    [0]=>
    string(4) "deny"
    [1]=>
    string(5) "allow"
  }
  ["accessControl"]=>
  string(6) "access"
}
array(0) {
}
array(7) {
  ["cmd"]=>
  string(8) "netmount"
  ["protocol"]=>
  string(7) "dropbox"
  ["host"]=>
  string(11) "dropbox.com"
  ["user"]=>
  string(4) "init"
  ["pass"]=>
  string(4) "init"
  ["options"]=>
  array(2) {
    ["url"]=>
    string(25) "php/connector.minimal.php"
    ["id"]=>
    string(8) "elfinder"
  }
  ["_"]=>
  string(13) "1449986007016"
}

array(7) {
  ["driver"]=>
  string(15) "LocalFileSystem"
  ["path"]=>
  string(9) "../files/"
  ["URL"]=>
  string(23) "/elfinder/php/../files/"
  ["uploadDeny"]=>
  array(1) {
    [0]=>
    string(3) "all"
  }
  ["uploadAllow"]=>
  array(2) {
    [0]=>
    string(5) "image"
    [1]=>
    string(10) "text/plain"
  }
  ["uploadOrder"]=>
  array(2) {
    [0]=>
    string(4) "deny"
    [1]=>
    string(5) "allow"
  }
  ["accessControl"]=>
  string(6) "access"
}
array(0) {
}
array(7) {
  ["cmd"]=>
  string(8) "netmount"
  ["protocol"]=>
  string(7) "dropbox"
  ["host"]=>
  string(7) "dropbox"
  ["path"]=>
  string(1) "/"
  ["user"]=>
  string(4) "done"
  ["pass"]=>
  string(4) "done"
  ["_"]=>
  string(13) "1449986007017"
}

array(7) {
  ["host"]=>
  string(7) "dropbox"
  ["path"]=>
  string(1) "/"
  ["consumerKey"]=>
  string(15) "xxxxxxxx"
  ["consumerSecret"]=>
  string(15) "xxxxxxxx"
  ["accessTokenSecret"]=>
  string(15) "xxxxxxxx"
  ["accessToken"]=>
  string(16) "xxxxxxxx"
  ["dropboxUid"]=>
  string(9) "xxxxxxxx"
}
array(0) {
}
array(7) {
  ["cmd"]=>
  string(8) "netmount"
  ["protocol"]=>
  string(7) "dropbox"
  ["host"]=>
  string(7) "dropbox"
  ["path"]=>
  string(1) "/"
  ["user"]=>
  string(4) "done"
  ["pass"]=>
  string(4) "done"
  ["_"]=>
  string(13) "1449986007017"
}

**Comment by nao-pon** [comment]
Thanks! I found the bug on windows server. Please wait fixes.

**Comment by nao-pon** [comment]
I fixed it. Please try newly nightly. Thanks! :+1:

**Comment by nao-pon** [comment]
@rajasharma27 At first, Please remove files `.elFinder_dropbox_db_*` in files/.tmb directory.

**Comment by rajasharma27** [comment]
thanks sir, 
not it is working ok

**Comment by nao-pon** [comment]
Do you remove files `.elFinder_dropbox_db_*`? As a precaution also please restart browser.

**Comment by rajasharma27** [comment]
yes
now full dropbox is working
thanks

**Comment by nao-pon** [comment]
:+1:

**Comment by rajasharma27** [comment]
sir, when connect full dropbox then unmount option missing from menu.

**Comment by rajasharma27** [comment]
ok done with    'mimeDetect'    => 'finfo'
